import Head from 'next/head'
import Image from 'next/image'
import Select from '../components/select/select';
import styles from '../styles/Home.module.css'

export default function Home(props) {
  console.log("Home => props", props);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Select</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
        <Select
          data={props.data.slice(0, 200)}
        />
      </main>


    </div>
  )
}

export async function getServerSideProps(context) {
  let data = []

  await fetch("https://api.coinpaprika.com/v1/coins")
    .then((response) => response.json())
    .then(response => {
      data = response
    })
    .catch(error => console.eror("error ", error))

  return {
    props: { data },
  }
}

