import Head from 'next/head'
import { useEffect, useState } from 'react';
import Select from '../components/SelectBox/SelectBox';

export default function Home(props) {
  // console.log("Home => props", props);
  const [data, setData] = useState([])

  const sortByName = (a, b) => {
    if (a.name.toLowerCase() < b.name.toLowerCase()) {
      return -1;
    }
    if (a.name.toLowerCase() > b.name.toLowerCase()) {
      return 1;
    }
    return 0;
  }

  useEffect(() => {
    if (!props.data.length) return
    const slicedData = props.data.slice(0, 200)
    const sortedData = slicedData.sort(sortByName);
    setData(sortedData)
  }, [props.data])

  const getSelectedItems = (selected) => {
    // console.log('====================================');
    // console.log("selected items in parent component", selected);
    // console.log('====================================');
  }


  return (
    <div>
      <Head>
        <title>Create Select</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
        <Select
          data={data}
          getSelectedItems={getSelectedItems}
        />
      </main>
    </div>
  )
}

export async function getServerSideProps(context) {
  let data = []

  await fetch("https://api.coinpaprika.com/v1/coins")
    .then((response) => response.json())
    .then(response => {
      data = response
    })
    .catch(error => console.eror("error ", error))

  return {
    props: {
      data
    },
  }
}

