import Head from 'next/head'
import { useEffect, useState } from 'react';
import { apiGetAllCoins } from '../api/apiCoins';
import { sortByName } from '../components/functions';
import MultiSelectComponent from '../components/MultiSelectComponent/MultiSelectComponent';
import OneSelectComponent from '../components/OneSelectComponent/OneSelectComponent';

export default function Home(props) {
  const [data, setData] = useState([])

  useEffect(() => {
    if (!props.data.length) return
    const slicedData = props.data.slice(0, 200)
    const sortedData = slicedData.sort(sortByName);
    setData(sortedData)
  }, [props.data])


  if (props.data.error) {
    return <h2>{props.data.error}</h2>
  }
  return (
    <div>
      <Head>
        <title>Create SelectBox</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
        <OneSelectComponent
          title='Industry'
          data={data}
        />

        <MultiSelectComponent
          title='location'
          data={data}
        />
      </main>
    </div>
  )
}

export async function getServerSideProps(context) {
  let data = []

  await apiGetAllCoins()
    .then(response => {
      data = response
    })
    .catch(error => {
      console.log("error ", error)
      data = { error: "Fetching data failed ..." }
    })

  return {
    props: {
      data
    },
  }
}

